// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PipeManagmentApp.Data;

#nullable disable

namespace PipeManagmentApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PipeManagmentApp.Data.Models.Package", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("packageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("packageNumber")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("PipeManagmentApp.Data.Models.Pipe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("dimensions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("number")
                        .HasColumnType("integer");

                    b.Property<int?>("packageId")
                        .HasColumnType("integer");

                    b.Property<string>("quality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("steelGrade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("weight")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.HasIndex("packageId");

                    b.ToTable("Pipes");
                });

            modelBuilder.Entity("PipeManagmentApp.Data.Models.Pipe", b =>
                {
                    b.HasOne("PipeManagmentApp.Data.Models.Package", "package")
                        .WithMany("pipes")
                        .HasForeignKey("packageId");

                    b.Navigation("package");
                });

            modelBuilder.Entity("PipeManagmentApp.Data.Models.Package", b =>
                {
                    b.Navigation("pipes");
                });
#pragma warning restore 612, 618
        }
    }
}
